const { describe, it, beforeEach, afterEach } = require('node:test')
const { buildRepositoryEditedEvent, initializeNock, loadInstance, mockAdminRepository, repository, teardownNock } = require('../common')

describe('repository.edited trigger', function () {
  let probot, githubScope

  beforeEach(async () => {
    githubScope = initializeNock()
    probot = await loadInstance()
  })

  afterEach(() => {
    teardownNock(githubScope)
  })

  it('does not apply configuration to edits generated by a bot', async () => {
    await probot.receive({
      name: 'repository.edited',
      payload: {
        changes: {},
        repository,
        organization: { login: repository.owner.login },
        sender: { id: 3, login: 'safe-settings[bot]', type: 'Bot' },
        installation: { id: 4, account: { login: repository.owner.login } }
      }
    })
  })

  it('does not apply configuration when the repository does not have a settings.yml', async () => {
    mockAdminRepository(githubScope)

    await probot.receive(buildRepositoryEditedEvent())
  })
})
